services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data # 이 설정은 Docker 볼륨을 /data 디렉토리에 마운트하여, 컨테이너가 삭제되더라도 데이터를 유지하도록 합니다.
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jin
      - MONGO_INITDB_ROOT_PASSWORD=1234

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always # 컨테이너가 중지되거나 실패할 경우 자동으로 다시 시작하도록 설정
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jin  # MongoDB 서비스와 일치하도록 'root' 사용
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234  # MongoDB 서비스의 비밀번호와 일치해야 함
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {} # Mongo라는 이름의 Docker 볼륨을 정의하여, MongoDB 데이터가 이곳에 저장됩니다.
